name: Deploy con secretos

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inyectar URL del NAS
        run: |
          PB_URL=$(echo "${{ secrets.PB_URL }}" | tr -d '\n\r ')
          cat index.html | sed "s|__PB_URL__|${PB_URL}|g" > index_new.html
          mv index_new.html index.html

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
